on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - use: ./.github/actions/node/setup
        with:
          node-version: ${{ inputs.node-version }}
      - name: Check code formatting
        run: pnpm format:check
