name: Node.js Setup
description: Checkout, setup Node.js and install dependencies

inputs:
  node-version:
    description: Node.js version to use
    required: true
  pnpm-version:
    description: pnpm version to use
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
    - name: Setup pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320  # v5.0.0
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    # --frozen-lockfile ensures reproducible builds by failing if lockfile is outdated
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
