on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string
    outputs:
      artifact-id:
        description: The ID of the uploaded artifact
        value: ${{ jobs.Build.outputs.artifact-id }}

permissions:
  contents: read
  actions: write  # required by actions/upload-artifact

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - uses: tylerkelly13/.github/.github/actions/node-setup@main
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}
      - name: Build package
        run: pnpm build
      - name: Generate Package
        run: pnpm pack --pack-destination artifacts
      - name: Generate checksums
        run: |
          mkdir -p artifacts/checksums
          sha256sum artifacts/*.tgz > artifacts/checksums/sha256.txt
      - name: Upload artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          path: artifacts
          if-no-files-found: error
