name: Build and Check

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string
    outputs:
      artifact-id:
        description: The ID of the uploaded build artifact
        value: ${{ jobs.Build.outputs.artifact-id }}

concurrency:
  group: checks-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  TypeCheck:
    uses: ./.github/workflows/node-typecheck.yml
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  Linting:
    uses: ./.github/workflows/node-lint.yml
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  Formatting:
    uses: ./.github/workflows/node-formatting.yml
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  Build:
    uses: ./.github/workflows/node-build.yml
    needs: [TypeCheck, Linting, Formatting]
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  Tests:
    uses: ./.github/workflows/node-test.yml
    needs: [Build]
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}
