on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: tylerkelly13/.github/.github/actions/node-setup@main
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}
      - name: Run tests
        run: pnpm test:coverage
