name: Deploy

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      pnpm-version:
        required: true
        type: string

concurrency:
  group: deploy
  cancel-in-progress: true


jobs:
  Build:
    uses: tylerkelly13/.github/.github/workflows/node-build.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}
  
  Linting:
    uses: tylerkelly13/.github/.github/workflows/node-lint.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  Formatting:
    uses: tylerkelly13/.github/.github/workflows/node-formatting.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  Tests:
    uses: tylerkelly13/.github/.github/workflows/node-test.yml@main
    with:
      node-version: ${{ inputs.node-version }}
      pnpm-version: ${{ inputs.pnpm-version }}

  Release:
    needs: [ Build, Linting, Formatting, Tests ]
    uses: tylerkelly13/.github/.github/workflows/node-gh-release.yml@main
    with:
      artifact-id: ${{ needs.Build.outputs.artifact-id }}