on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: tylerkelly13/.github/.github/actions/node-setup@main
        with:
          node-version: ${{ inputs.node-version }}
      - name: Lint code
        run: pnpm lint
