on:
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8
        with:
          artifact-ids: ${{ inputs.artifact-id }}
          path: artifacts

      # gate release creation on tag push
      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda  # v3.0.0
        if: github.ref_type == 'tag'
        with:
          files: |
            artifacts/*.tgz
            artifacts/checksums/*.txt
          draft: true
          generate_release_notes: true