on:
  workflow_call:
    outputs:
      artifact-id:
        description: The ID of the uploaded artifact
        value: ${{ jobs.Build.outputs.artifact-id }}

jobs:
  Build:
    runs-on: ubuntu-22.04
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - uses: tylerkelly13/.github/.github/actions/cargo-setup@main
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build project
        run: just build
      - name: Generate Package
        run: just deb
      - name: Generate checksums
        run: |
          mkdir -p target/debian/checksums
          shasum -a 256 target/debian/*.deb > target/debian/checksums/sha256.txt
      - name: Upload artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@v6
        with:
          path: target/debian
          if-no-files-found: error
