on:
  workflow_call:
    inputs:
      container-image:
        description: Docker image to run the job in
        required: false
        default: ''
        type: string
    outputs:
      artifact-id:
        description: The ID of the uploaded artifact
        value: ${{ jobs.Build.outputs.artifact-id }}

permissions:
  contents: read
  actions: write  # required by actions/upload-artifact

jobs:
  Build:
    runs-on: ubuntu-latest
    container: ${{ inputs.container-image || '' }}
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - uses: tylerkelly13/.github/.github/actions/cargo-setup@main
      - name: Build project
        run: just build
      - name: Generate Package
        run: just deb
      - name: Generate checksums
        run: |
          mkdir -p target/debian/checksums
          sha256sum target/debian/*.deb > target/debian/checksums/sha256.txt
      - name: Upload artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@v6
        with:
          path: target/debian
          if-no-files-found: error
