on:
  workflow_call:
    inputs:
      enabled:
        description: Whether to run coverage
        required: true
        type: boolean
      container-image:
        description: Docker image to run the job in
        required: false
        default: ''
        type: string

permissions:
  contents: read

jobs:
  Coverage:
    # allows callers to skip coverage report
    if: ${{ inputs.enabled }}
    runs-on: ubuntu-latest
    container: ${{ inputs.container-image || '' }}
    steps:
      - uses: tylerkelly13/.github/.github/actions/cargo-setup@8d7d2e6616254a836736b88f3eb078caf96716db  # cargo-setup-civ1
        with:
          container-image: ${{ inputs.container-image }}
      # On bare runners, install cargo-tarpaulin for coverage reporting
      - name: Install cargo-tarpaulin
        if: inputs.container-image == ''
        uses: taiki-e/install-action@07b4745e0c39a41822af610387492e3e53aa222b  # v2
        with:
          tool: cargo-tarpaulin
      - name: Report test coverage
        run: just coverage
