on:
  workflow_call:
    inputs:
      artifact-id:
        required: true
        type: string

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8
        with:
          artifact-ids: ${{ inputs.artifact-id }}
          path: target/debian

      # only create a release when triggered by a tag push
      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  # v3.0.2
        if: github.ref_type == 'tag'
        with:
          files: |
            target/debian/*.deb
            target/debian/checksums/*.txt
          draft: true
          generate_release_notes: true